### ISSUE TITLE
PROJ > Website Review

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/whygriefmatters.org#21]
# Background and Context

Following deployment of the initial version of the site this issue tracks outputs from the first scheduled review

## Pre-meeting Feedback

- [x] https://github.com/grief-matters/grief-matters-cms/issues/125
- [x] https://github.com/grief-matters/grief-matters-cms/issues/126
- [x] https://github.com/grief-matters/grief-matters-cms/issues/127
- [x] grief-matters/whygriefmatters.org#43 
- [x] grief-matters/whygriefmatters.org#44
- [x] grief-matters/whygriefmatters.org#31 
- [x] grief-matters/grief-matters-cms#131
- [x] grief-matters/whygriefmatters.org#52
- [x] grief-matters/whygriefmatters.org#51
- [x] grief-matters/whygriefmatters.org#50
- [x] #55

Some tasks moved to #72 

## Decisions To Make

- 'Contribute' page - we can either remove it for now or have a "Coming Soon" page - maybe even with a contact form to get in touch so you can start to collect a list of potential contributors?
- Featured Articles feature panel
- ~~Types of Loss feature panel~~
- Should be easy enough to explore slightly different layouts where there are less than 3 'Featured...' - we shouldn't have to worry about the number due to presentational concerns
- Buttons 3Dness - we could look at making the drop shadow heavier, and add a subtle outline, apply a hover transform etc.

## Notes

- Custom color palettes i.e. Core Values - out of scope for now things above high priority for now
- Bring in Jamie to help with putting together the Feature Panels
- Contacted Jamie about whether logos are in the CMS or that still needs to be done
- Clarification for:
> It would be nice if visitors could see more articles/stories/support groups at once, once they get past the Featured Articles and Featured Stories and click on "all stories on XXX." If they could see several titles at once, it would be easier for them to figure out what titles were of most interest to them.
