### ISSUE TITLE
Website Pre-launch Tasks

### ISSUE THREAD

**Issue by danlechambre** [grief-matters/whygriefmatters.org#72]
## Tasks Captured At Last Review

Tasks captured at last website review that may still be outstanding:

- [ ] grief-matters/whygriefmatters.org#32 
- [x] https://github.com/grief-matters/grief-matters-cms/issues/116
- [ ] grief-matters/whygriefmatters.org#47
- [x] grief-matters/grief-matters-cms#132
- [ ] grief-matters/whygriefmatters.org#49
- [x] https://github.com/grief-matters/grief-matters-cms/issues/129
- [x] https://github.com/grief-matters/grief-matters-cms/issues/130
- [x] grief-matters/grief-matters-cms#133
- [x] #54
- [ ] grief-matters/whygriefmatters.org#40 
- [x] grief-matters/whygriefmatters.org#13 

## Tasks Surfaced 26th November 2024

- [x] #73
- [ ] #95
- [x] #86
- [ ] ~~Add Non-profit status somewhere to site~~
- [x] #85
- [x] #68 
- [ ] #39 
- [ ] #33 
- [x] #87
- [x] #70 
- [ ] #96 
- [ ] #111
- [x] #83
- [x] Decide on resource ordering and implement throughout templates
- [x] #84
- [x] Mission Statement Revisions
- [ ] ~~Add Contact Information to the Footer~~
- [ ] #112
- [x] #90

## Further Identified

- [x] #12 
- [x] #88 

## Content Tasks

- [ ] ~~Add an additional row of photos for 'Topics We Cover'~~ content tasks moved out of Github
- [ ] ~~Change Featured Articles/Stories Panels to have another row of "Featured Resources" instead of the article links (point 6 - in changes to home page document)~~ content change as above
- [ ] Changes to Feature Panels discussed in point 9 of "Changes to the Homepage" document
- [ ] "Notable Websites" changes discussed in point 10 of "Changes to Homepage" document
- [ ] Art Direction on problematic images
- [ ] Problems with COVID-19 content organization?

**Comment by danlechambre** [comment]
Closing down this issue after mostly all issues have been created and being tracked and prioritised separately
